Repository Gongju-Unity-Bootcamp/UNHOLY-Justice, pull requests merged in 2024-02, with the labels that each got.

#3 feat: Character Movement Added(#2)
  Unholy/Assets/Scenes/Character.meta
  Unholy/Assets/Scenes/Character.unity
  Unholy/Assets/Scenes/Character.unity.meta
  Unholy/Assets/Scenes/Character/GlobalVolumeProfile.asset
  Unholy/Assets/Scenes/Character/GlobalVolumeProfile.asset.meta
  Unholy/Assets/Scripts.meta
  Unholy/Assets/Scripts/PlayerInputs.cs
  Unholy/Assets/Scripts/PlayerInputs.cs.meta
  Unholy/Assets/Scripts/PlayerInputs.inputactions
  Unholy/Assets/Scripts/PlayerInputs.inputactions.meta
  Unholy/Assets/Scripts/Player_Movement.cs
  Unholy/Assets/Scripts/Player_Movement.cs.meta
  Unholy/Assets/Settings/URP-Balanced.asset
  Unholy/Assets/Settings/URP-HighFidelity-Renderer.asset
  Unholy/Assets/Settings/URP-HighFidelity.asset
  Unholy/Assets/Settings/URP-Performant.asset
  Unholy/Assets/UniversalRenderPipelineGlobalSettings.asset
  Unholy/Packages/manifest.json
  Unholy/Packages/packages-lock.json
  Unholy/ProjectSettings/ProjectSettings.asset
  Unholy/ProjectSettings/ShaderGraphSettings.asset
Labels: enhancement

#20 fix: Delete MonsterSpawner
  Unholy/Assets/Scenes/gang.meta
  Unholy/Assets/Scenes/gang/Prefabs.meta
  Unholy/Assets/Scenes/gang/Prefabs/Monster.prefab
  Unholy/Assets/Scenes/gang/Prefabs/Monster.prefab.meta
  Unholy/Assets/Scenes/gang/Scenes.meta
  Unholy/Assets/Scenes/gang/Scenes/Monster.unity
  Unholy/Assets/Scenes/gang/Scenes/Monster.unity.meta
  Unholy/Assets/Scenes/gang/Scripts.meta
  Unholy/Assets/Scenes/gang/Scripts/MonsterSpawner.cs
  Unholy/Assets/Scenes/gang/Scripts/MonsterSpawner.cs.meta
Labels: documentation

#26 feat: Boss AI with behavior tree Added(#24)
  Unholy/Assets/Animations/Monster/Boss_BA_Attack.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_BA_BackStep.fbx
  Unholy/Assets/Animations/Monster/Boss_BA_BackStep.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Combo_Attack_2Hit.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Combo_Attack_3Hit.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Die.fbx
  Unholy/Assets/Animations/Monster/Boss_Die.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Hit.FBX
  Unholy/Assets/Animations/Monster/Boss_Hit.FBX.meta
  Unholy/Assets/Animations/Monster/Boss_Idle.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Jump_Attack.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Kick_Attack.fbx
  Unholy/Assets/Animations/Monster/Boss_Kick_Attack.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Normal_Attack1.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Normal_Attack2.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Track.fbx
  Unholy/Assets/Animations/Monster/Boss_Track.fbx.meta
  Unholy/Assets/Animations/Monster/minotaur1@attack1.fbx
  Unholy/Assets/Animations/Monster/minotaur1@attack1.fbx.meta
  Unholy/Assets/Animations/Monster/minotaur1@attack2.fbx
  Unholy/Assets/Animations/Monster/minotaur1@attack2.fbx.meta
  Unholy/Assets/Animations/Monster/minotaur1@attack3.fbx
  Unholy/Assets/Animations/Monster/minotaur1@attack3.fbx.meta
  Unholy/Assets/Animations/Monster/minotaur1@attack4_kick.fbx.meta
  Unholy/Assets/Animations/Monster/minotaur1@attack5_kick.fbx
  Unholy/Assets/Animations/Monster/minotaur1@attack5_kick.fbx.meta
  Unholy/Assets/Animations/Monster/minotaur1@hit_2.fbx
  Unholy/Assets/Animations/Monster/minotaur1@hit_2.fbx.meta
  Unholy/Assets/Animations/Monster/minotaur1@idle.fbx
  Unholy/Assets/Animations/Monster/minotaur1@run.fbx
  Unholy/Assets/Animations/Monster/minotaur1@run.fbx.meta
  Unholy/Assets/Animations/Monster/minotaur1@run_strafe_left45.fbx
  Unholy/Assets/Animations/Monster/minotaur1@run_strafe_left45.fbx.meta
  Unholy/Assets/Animations/Monster/minotaur1@run_strafe_right45.fbx
  Unholy/Assets/Animations/Monster/minotaur1@run_strafe_right45.fbx.meta
  Unholy/Assets/Animations/Monster/minotaur1@walk_back.fbx
  Unholy/Assets/Animations/Monster/minotaur1@walk_back.fbx.meta
  Unholy/Assets/Animations/Monster/minotaur1@walk_forward.fbx
  Unholy/Assets/Animations/Monster/minotaur1@walk_forward.fbx.meta
  Unholy/Assets/Animations/Monster/minotaur1@walk_forward2.fbx
  Unholy/Assets/Animations/Monster/minotaur1@walk_forward2.fbx.meta
  Unholy/Assets/Models/Monster/Materials.meta
  Unholy/Assets/Models/Monster/Materials/mat_minotaur1_axe.mat
  Unholy/Assets/Models/Monster/Materials/mat_minotaur1_axe.mat.meta
  Unholy/Assets/Models/Monster/Materials/mat_minotaur1_body.mat
  Unholy/Assets/Models/Monster/Materials/mat_minotaur1_body.mat.meta
  Unholy/Assets/Scenes/BT.meta
  Unholy/Assets/Scenes/BT/Ani Crtl.meta
  Unholy/Assets/Scenes/BT/Ani Crtl/minotaur1_Animator_Controller.controller
  Unholy/Assets/Scenes/BT/Ani Crtl/minotaur1_Animator_Controller.controller.meta
  Unholy/Assets/Scenes/BT/BT Test.unity
  Unholy/Assets/Scenes/BT/BT Test.unity.meta
  Unholy/Assets/Scenes/BT/Script.meta
  Unholy/Assets/Scenes/BT/Script/Behavior Tree.cs
  Unholy/Assets/Scenes/BT/Script/Behavior Tree.cs.meta
  Unholy/Assets/Scenes/BT/Script/BossAI.cs
  Unholy/Assets/Scenes/BT/Script/BossAI.cs.meta
Labels: enhancement

#40 [feat] Input System 이동키, jump키, sprint키 binding 및 간단한 이동 (#25)
  Unholy/Assets/Animation Controller/PlayerController.controller
  Unholy/Assets/Animation Controller/PlayerController.controller.meta
  Unholy/Assets/Animations/Player/Unarmed/P_UnArm_Walk.fbx
  Unholy/Assets/Animations/Player/Unarmed/P_UnArm_Walk.fbx.meta
  Unholy/Assets/ExplosiveLLC.meta
  Unholy/Assets/ExplosiveLLC/RPG Character Mecanim Animation Pack FREE.meta
  Unholy/Assets/ExplosiveLLC/RPG Character Mecanim Animation Pack FREE/InputSystem - Requires InputSystem Package.unitypackage.meta
  Unholy/Assets/ExplosiveLLC/Warrior FREE.meta
  Unholy/Assets/ExplosiveLLC/Warrior FREE/InputSystem Support - Requires InputSystem Package.unitypackage.meta
  Unholy/Assets/InputSystem.inputsettings.asset
  Unholy/Assets/InputSystem.inputsettings.asset.meta
  Unholy/Assets/Scenes/Character.unity
  Unholy/Assets/Scripts/Player/PlayerAnimation.cs
  Unholy/Assets/Scripts/Player/PlayerAnimation.cs.meta
  Unholy/Assets/Scripts/Player/PlayerController.cs
  Unholy/Assets/Scripts/Player/PlayerController.cs.meta
  Unholy/Assets/Scripts/Player/PlayerInputManager.cs
  Unholy/Assets/Scripts/Player/PlayerInputManager.cs.meta
  Unholy/Assets/Scripts/Player/PlayerInputs.cs
  Unholy/Assets/Scripts/Player/Player_Movement.cs
  Unholy/Assets/Scripts/Player/testController.cs
  Unholy/Assets/Scripts/Player/testController.cs.meta
  Unholy/Assets/Scripts/Player/testInputs.cs
  Unholy/Assets/Scripts/Player/testInputs.cs.meta
  Unholy/Assets/Scripts/Player/testInputs.inputactions
  Unholy/Assets/Scripts/Player/testInputs.inputactions.meta
  Unholy/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#43 feat: Player 이동 및 회전 (#28)
  Unholy/Assets/Scenes/Character.unity
  Unholy/Assets/Scripts/Player/PlayerBehaviour.cs
  Unholy/Assets/Scripts/Player/PlayerBehaviour.cs.meta
  Unholy/Assets/Scripts/Player/PlayerController.cs
  Unholy/Assets/Scripts/Player/PlayerInputManager.cs
  Unholy/Assets/Scripts/Player/PlayerInputManager.cs.meta
  Unholy/Assets/Scripts/Player/Player_Movement.cs
  Unholy/Assets/Scripts/Player/Player_Movement.cs.meta
  Unholy/Assets/Scripts/Player/testController.cs
  Unholy/Assets/Scripts/Player/testController.cs.meta
  Unholy/Assets/Scripts/Player/testInputs.cs
  Unholy/Assets/Scripts/Player/testInputs.inputactions
  Unholy/Assets/Scripts/Player/testInputs.inputactions.meta
Labels: enhancement

#46 feat: Player unarmed FSM - movement - walk animation 구현 (#29)
  Unholy/Assets/Animation Controller/PlayerController.controller
  Unholy/Assets/Animation Controller/PlayerController.controller.meta
  Unholy/Assets/Scenes/Character.unity
  Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs
  Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs.meta
  Unholy/Assets/Scripts/Player/PlayerAnimation.cs
  Unholy/Assets/Scripts/Player/PlayerBehaviour.cs
  Unholy/Assets/Scripts/Player/PlayerController.cs
Labels: enhancement

#47 feat: Player unarmed FSM - movement - sprint 구현 (#30)
  Unholy/Assets/Animation Controller/PlayerController.controller
  Unholy/Assets/Animation Controller/PlayerController.controller.meta
  Unholy/Assets/Animations/Player/Unarmed/P_UnArm_Sprint-Forward.FBX.meta
  Unholy/Assets/Scenes/Character.unity
  Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs
  Unholy/Assets/Scripts/Player/PlayerAnimation.cs
  Unholy/Assets/Scripts/Player/PlayerBehaviour.cs
  Unholy/Assets/Scripts/Player/PlayerController.cs
Labels: enhancement

#48 feat: Player unarmed FSM - Jump 구현 (#31)
  Unholy/Assets/Animation Controller/PlayerController.controller
  Unholy/Assets/Animation Controller/PlayerController.controller.meta
  Unholy/Assets/Animations/Player/Unarmed/P_UnArm_Fall.FBX.meta
  Unholy/Assets/Animations/Player/Unarmed/P_Unarmed_Land.fbx
  Unholy/Assets/Animations/Player/Unarmed/P_Unarmed_Land.fbx.meta
  Unholy/Assets/InputSystem.inputsettings.asset
  Unholy/Assets/Scenes/Character.unity
  Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs
  Unholy/Assets/Scripts/Player/PlayerAnimation.cs
  Unholy/Assets/Scripts/Player/PlayerBehaviour.cs
  Unholy/Assets/Scripts/Player/PlayerController.cs
  Unholy/Assets/Scripts/Player/PlayerInputs.cs
  Unholy/Assets/Scripts/Player/PlayerInputs.inputactions
  Unholy/ProjectSettings/TagManager.asset
Labels: enhancement

#49 feat: Player unarmed FSM dodge 구현 (#32)
  Unholy/Assets/Animation Controller/Dodge_Controller.controller
  Unholy/Assets/Animation Controller/Dodge_Controller.controller.meta
  Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs
  Unholy/Assets/Scripts/Player/PlayerAnimation.cs
  Unholy/Assets/Scripts/Player/PlayerBehaviour.cs
  Unholy/Assets/Scripts/Player/PlayerController.cs
  Unholy/Assets/Scripts/Player/PlayerInputs.cs
  Unholy/Assets/Scripts/Player/PlayerInputs.inputactions
Labels: enhancement

#50 feat: Player unarmed FSM damaged 구현(#33)
  Unholy/Assets/Animation Controller/Dodge_Controller.controller
  Unholy/Assets/Animation Controller/Dodge_Controller.controller.meta
  Unholy/Assets/Animation Controller/PlayerController.controller
  Unholy/Assets/Animation Controller/PlayerController.controller.meta
  Unholy/Assets/Scenes/Character.unity
  Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs
  Unholy/Assets/Scripts/Player/PlayerAnimation.cs
  Unholy/Assets/Scripts/Player/PlayerController.cs
  Unholy/ProjectSettings/TagManager.asset
Labels: enhancement

#54 feat: Monster(boss) Behavior Tree Build
  Unholy/Assets/Scenes/BT/Ani Crtl/minotaur1_Animator_Controller.controller
  Unholy/Assets/Scenes/BT/BT Test.unity
  Unholy/Assets/Scenes/BT/Script/BossAI.cs
  Unholy/Packages/manifest.json
  Unholy/Packages/packages-lock.json
  Unholy/ProjectSettings/PackageManagerSettings.asset
Labels: enhancement

#55 bug: Jump - Dodge animation 전환 오류 (#52)
  Unholy/Assets/Animation Controller/PlayerController.controller
  Unholy/Assets/ExplosiveLLC.meta
  Unholy/Assets/ExplosiveLLC/RPG Character Mecanim Animation Pack FREE.meta
  Unholy/Assets/ExplosiveLLC/RPG Character Mecanim Animation Pack FREE/InputSystem - Requires InputSystem Package.unitypackage.meta
  Unholy/Assets/ExplosiveLLC/Warrior FREE.meta
  Unholy/Assets/ExplosiveLLC/Warrior FREE/InputSystem Support - Requires InputSystem Package.unitypackage.meta
  Unholy/Assets/Scenes/Character.unity
  Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs
  Unholy/Assets/Scripts/Player/PlayerAnimation.cs
  Unholy/Assets/Scripts/Player/PlayerBehaviour.cs
  Unholy/Assets/Scripts/Player/PlayerController.cs
  Unholy/ProjectSettings/PackageManagerSettings.asset
Labels: bug

#57 feat: Apply each animation in the monster(boss) BT(#51)
  Unholy/Assets/Animations/Monster/Boss_Track.fbx.meta
  Unholy/Assets/Scenes/BT/Script/BossAI.cs
Labels: enhancement

#58 bug: 이동 중 연속 점프 시 애니메이션 전환 오류 (#56)
  Unholy/Assets/Animation Controller/PlayerController.controller
  Unholy/Assets/Scenes/Character.unity
  Unholy/Assets/Scripts/Player/PlayerAnimation.cs
  Unholy/Assets/Scripts/Player/PlayerBehaviour.cs
  Unholy/Assets/Scripts/Player/PlayerController.cs
Labels: bug

#60 feat: Camera Control 구현 (#59)
  Unholy/Assets/Scenes/Character.unity
  Unholy/Assets/Scripts/Player/PlayerBehaviour.cs
  Unholy/Assets/Scripts/Player/PlayerController.cs
Labels: enhancement

#61 feat: Player Melee FSM - Jump (#35)
  Unholy/Assets/Animation Controller/PlayerController.controller
  Unholy/Assets/Materials/Player/Two Hand/2Handed.mat
  Unholy/Assets/Scenes/Character.unity
  Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs
  Unholy/Assets/Scripts/Player/PlayerAnimation.cs
  Unholy/Assets/Scripts/Player/PlayerBehaviour.cs
  Unholy/Assets/Scripts/Player/PlayerController.cs
  Unholy/Assets/Scripts/Player/PlayerInputs.cs
  Unholy/Assets/Scripts/Player/PlayerInputs.inputactions
  Unholy/Assets/Scripts/Player/WeaponSwitch.cs
  Unholy/Assets/Scripts/Player/WeaponSwitch.cs.meta
  Unholy/Assets/Scripts/Player/WeaponType.cs
  Unholy/Assets/Scripts/Player/WeaponType.cs.meta
Labels: enhancement

#64 feat: Behavior tree rebuild - attack node(#63)
  Unholy/Assets/Animation Controller/MinoController.controller
  Unholy/Assets/Animation Controller/MinoController.controller.meta
  Unholy/Assets/Scenes/BT/Ani Crtl.meta
  Unholy/Assets/Scenes/BT/Script.meta
  Unholy/Assets/Scenes/BT/Script/Behavior Tree.cs
  Unholy/Assets/Scenes/BT/Script/BossAI.cs
  Unholy/Assets/Scenes/Monster.meta
  Unholy/Assets/Scenes/Monster/Monster.unity
  Unholy/Assets/Scenes/Monster/Monster.unity.meta
  Unholy/Assets/Scenes/SampleScene.unity
  Unholy/Assets/Scenes/SampleScene.unity.meta
  Unholy/Assets/Scripts/Monster/CustomAction.cs
  Unholy/Assets/Scripts/Monster/CustomAction.cs.meta
  Unholy/Assets/Scripts/Monster/MinoController.cs
  Unholy/Assets/Scripts/Monster/MinoController.cs.meta
Labels: enhancement

#66 feat: Player Melee FSM - Attack (#34)
  Unholy/Assets/Animation Controller/PlayerController.controller
  Unholy/Assets/Animations/Player/One Hand/P_One_Attack1.FBX.meta
  Unholy/Assets/Animations/Player/One Hand/P_One_Attack2.FBX.meta
  Unholy/Assets/Animations/Player/One Hand/P_One_Attack3.FBX.meta
  Unholy/Assets/Scenes/Character.unity
  Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs
  Unholy/Assets/Scripts/Player/PlayerAnimation.cs
  Unholy/Assets/Scripts/Player/PlayerBehaviour.cs
  Unholy/Assets/Scripts/Player/PlayerController.cs
  Unholy/Assets/Scripts/Player/PlayerInputs.cs
  Unholy/Assets/Scripts/Player/PlayerInputs.inputactions
  Unholy/Assets/Scripts/Player/WeaponSwitch.cs
Labels: enhancement

#69 bug: one hand dodge 오류 (#68)
  Unholy/Assets/Animation Controller/PlayerController.controller
  Unholy/Assets/Scenes/Character.unity
  Unholy/Assets/Scripts/Player/PlayerAnimation.cs
Labels: bug

#70 feat: Behavior Tree Rebuild - IsStateEnd(#65)
  Unholy/Assets/Animation Controller/MinoController.controller
  Unholy/Assets/Animations/Monster/Boss_BA_Attack.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_BA_BackStep.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Combo_Attack_2Hit.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Combo_Attack_3Hit.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Die.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Hit.FBX.meta
  Unholy/Assets/Animations/Monster/Boss_Jump_Attack.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Kick_Attack.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Normal_Attack1.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Normal_Attack2.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Track.fbx.meta
  Unholy/Assets/Scenes/Monster/Monster.unity
  Unholy/Assets/Scripts/Monster/BehaviorTreebuilderExtensitions.cs
  Unholy/Assets/Scripts/Monster/BehaviorTreebuilderExtensitions.cs.meta
  Unholy/Assets/Scripts/Monster/CustomAction.cs
  Unholy/Assets/Scripts/Monster/MinoController.cs
Labels: enhancement

#71 feat: Behavior tree rebuild(#62)
  Unholy/Assets/Animation Controller/MinoController.controller
  Unholy/Assets/Animations/Monster/Boss_BA_Attack.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_BA_BackStep.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Combo_Attack_2Hit.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Combo_Attack_3Hit.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Jump_Attack.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Kick_Attack.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Normal_Attack1.fbx.meta
  Unholy/Assets/Animations/Monster/Boss_Normal_Attack2.fbx.meta
  Unholy/Assets/Scenes/Monster/Monster.unity
  Unholy/Assets/Scripts/Monster/CustomAction.cs
  Unholy/Assets/Scripts/Monster/MinoController.cs
Labels: bug, enhancement

#77 refactor: Player 관련 코드 리팩토링 (#67)
  Unholy/Assets/Animation Controller/PlayerController.controller
  Unholy/Assets/Materials/Player/Two Hand/2Handed.mat
  Unholy/Assets/Prefabs/Player/Player.prefab
  Unholy/Assets/Prefabs/Player/Player.prefab.meta
  Unholy/Assets/Scenes/Character.unity
  Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs
  Unholy/Assets/Scripts/Player/PlayerAnimation.cs
  Unholy/Assets/Scripts/Player/PlayerBehaviour.cs
  Unholy/Assets/Scripts/Player/PlayerController.cs
  Unholy/Assets/Scripts/Player/StateBehaviour.meta
  Unholy/Assets/Scripts/Player/StateBehaviour/ComboAttackBehaviour.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/ComboAttackBehaviour.cs.meta
  Unholy/Assets/Scripts/Player/StateBehaviour/DodgeBehaviour.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/DodgeBehaviour.cs.meta
  Unholy/Assets/Scripts/Player/StateBehaviour/JumpAttackBehaviour.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/JumpAttackBehaviour.cs.meta
  Unholy/Assets/Scripts/Player/StateBehaviour/JumpBehaviour.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/JumpBehaviour.cs.meta
  Unholy/Assets/Scripts/Player/WeaponSwitch.cs
Labels: refactoring

#82 feat: Player Upper Body FSM (#39)
  Unholy/Assets/Animation Controller/PlayerController.controller
  Unholy/Assets/Animation Controller/Upper Body.mask
  Unholy/Assets/Animation Controller/Upper Body.mask.meta
  Unholy/Assets/Scenes/Character.unity
  Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs
  Unholy/Assets/Scripts/Player/PlayerController.cs
  Unholy/Assets/Scripts/Player/PlayerInputs.cs
  Unholy/Assets/Scripts/Player/PlayerInputs.inputactions
Labels: enhancement

#83 feat: Add Monster(Boss) NavMeshAgent (#76)
  Unholy/Assets/Animation Controller/MinoController.controller
  Unholy/Assets/Animations/Monster/B_Combo_Attack_2Hit.fbx.meta
  Unholy/Assets/Animations/Monster/B_Combo_Attack_3Hit.fbx.meta
  Unholy/Assets/Animations/Monster/B_Normal_Attack1.fbx.meta
  Unholy/Assets/Animations/Monster/B_Normal_Attack2.fbx.meta
  Unholy/Assets/Scenes/Monster/Monster.meta
  Unholy/Assets/Scenes/Monster/Monster.unity
  Unholy/Assets/Scenes/Monster/Monster/NavMesh-Plane.asset
  Unholy/Assets/Scenes/Monster/Monster/NavMesh-Plane.asset.meta
  Unholy/Assets/Scripts/Monster/MinoController.cs
  Unholy/Assets/Scripts/Monster/StateAction.cs
  Unholy/Packages/manifest.json
  Unholy/Packages/packages-lock.json
  Unholy/ProjectSettings/NavMeshAreas.asset
Labels: enhancement

#87 feat: Player Melee FSM - Defense (#36-1)
  Unholy/Assets/Animation Controller/PlayerController.controller
  Unholy/Assets/Scenes/Character.unity
  Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs
  Unholy/Assets/Scripts/Player/PlayerController.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/AttackBehaviour.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/ComboAttackBehaviour.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/DefenseBehaviour.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/DefenseBehaviour.cs.meta
  Unholy/Assets/Scripts/Player/StateBehaviour/DodgeBehaviour.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/JumpAttackBehaviour.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/JumpBehaviour.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/WeaponSwitchBehaviour.cs
  Unholy/Assets/Scripts/Player/WeaponSwitch.cs
Labels: enhancement

#88 feat: Monster(Boss) hit state(Parrying)(#85)
  Unholy/Assets/Animation Controller/MinoController.controller
  Unholy/Assets/Animations/Monster/B_BA_BackStep.fbx
  Unholy/Assets/Animations/Monster/B_BA_BackStep.fbx.meta
  Unholy/Assets/ParryingBehaviour.cs
  Unholy/Assets/ParryingBehaviour.cs.meta
  Unholy/Assets/Prefabs/Monster/minotaur1.prefab
  Unholy/Assets/Scenes/Monster/Monster.unity
  Unholy/Assets/Scripts/Monster/MinoController.cs
Labels: enhancement

#91 feat: Parrying 구현 (#90)
  Unholy/Assets/Animation Controller/MinoController.controller
  Unholy/Assets/Animation Controller/PlayerController.controller
  Unholy/Assets/Scenes/Monster/Monster.unity
  Unholy/Assets/Scripts/Monster/MinoController.cs
  Unholy/Assets/Scripts/Monster/StateBehaviour.meta
  Unholy/Assets/Scripts/Monster/StateBehaviour/ParryingBehaviour.cs
  Unholy/Assets/Scripts/Monster/StateBehaviour/ParryingBehaviour.cs.meta
  Unholy/Assets/Scripts/Player/PlayerController.cs
Labels: enhancement

#99 feat: 전투시스템 (#19)
  Unholy/Assets/Animation Controller/MinoController.controller
  Unholy/Assets/Animation Controller/PlayerController.controller
  Unholy/Assets/Animations/Monster/B_Look.fbx
  Unholy/Assets/Animations/Monster/B_Look.fbx.meta
  Unholy/Assets/Animations/Player/One Hand/P_One_Attack1_M.FBX.meta
  Unholy/Assets/Animations/Player/One Hand/P_One_Attack2_M.FBX.meta
  Unholy/Assets/Animations/Player/One Hand/P_One_Attack3_M.FBX.meta
  Unholy/Assets/Animations/Player/One Hand/P_One_Attack_Jump.FBX.meta
  Unholy/Assets/Animations/Player/One Hand/P_One_BlockBreak.FBX
  Unholy/Assets/Animations/Player/One Hand/P_One_BlockBreak.FBX.meta
  Unholy/Assets/Animations/Player/One Hand/P_One_Hit.FBX
  Unholy/Assets/Animations/Player/One Hand/P_One_Hit.FBX.meta
  Unholy/Assets/Animations/Player/Two Hand/P_Two_Attack1_M.FBX.meta
  Unholy/Assets/Animations/Player/Two Hand/P_Two_Attack2_M.FBX.meta
  Unholy/Assets/Animations/Player/Two Hand/P_Two_Attack3_M.FBX.meta
  Unholy/Assets/Animations/Player/Two Hand/P_Two_Attack_Jump.FBX.meta
  Unholy/Assets/Animations/Player/Two Hand/P_Two_BlockBreak.FBX
  Unholy/Assets/Animations/Player/Two Hand/P_Two_BlockBreak.FBX.meta
  Unholy/Assets/Prefabs/Monster/minotaur1.prefab
  Unholy/Assets/Prefabs/Player UI Manager(temp).prefab
  Unholy/Assets/Prefabs/Player UI Manager(temp).prefab.meta
  Unholy/Assets/Prefabs/Player/Player.prefab
  Unholy/Assets/Scenes/Monster/Monster.unity
  Unholy/Assets/Scenes/Monster/Monster/NavMesh-Ground.asset
  Unholy/Assets/Scenes/Monster/Monster/NavMesh-Ground.asset.meta
  Unholy/Assets/Scripts/CombatManager.cs
  Unholy/Assets/Scripts/CombatManager.cs.meta
  Unholy/Assets/Scripts/Monster/MinoCollider.cs
  Unholy/Assets/Scripts/Monster/MinoCollider.cs.meta
  Unholy/Assets/Scripts/Monster/MinoController.cs
  Unholy/Assets/Scripts/Monster/StateBehaviour/ParryingBehaviour.cs
  Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs
  Unholy/Assets/Scripts/Player/PlayerAttackCollision.cs
  Unholy/Assets/Scripts/Player/PlayerAttackCollision.cs.meta
  Unholy/Assets/Scripts/Player/PlayerController.cs
  Unholy/Assets/Scripts/Player/StaminaValues.cs
  Unholy/Assets/Scripts/Player/StaminaValues.cs.meta
  Unholy/Assets/Scripts/Player/StateBehaviour/AttackBehaviour.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/DamagedBehaviour.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/DamagedBehaviour.cs.meta
  Unholy/Assets/Scripts/Player/StateBehaviour/DodgeBehaviour.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/IdleBehaviour.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/IdleBehaviour.cs.meta
  Unholy/Assets/Scripts/Player/StateBehaviour/JumpAttackBehaviour.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/JumpBehaviour.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/MovementBehaviour.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/MovementBehaviour.cs.meta
  Unholy/Assets/Scripts/Player/StateBehaviour/WeaponSwitchBehaviour.cs
  Unholy/Assets/Scripts/Player/WeaponSwitch.cs
  Unholy/Assets/Scripts/Player/WeaponType.cs
  Unholy/Assets/Scripts/UIStatBar.cs
  Unholy/Assets/Scripts/UIStatBar.cs.meta
  Unholy/ProjectSettings/TagManager.asset
Labels: enhancement

#104 feat: 전투 특수효과 (#81)
  Unholy/Assets/Animation Controller/MinoController.controller
  Unholy/Assets/Animations/Monster/B_Combo_Attack_2Hit.fbx.meta
  Unholy/Assets/Animations/Monster/B_Combo_Attack_3Hit.fbx.meta
  Unholy/Assets/Animations/Monster/B_Jump_Attack.fbx.meta
  Unholy/Assets/Animations/Monster/B_Normal_Attack1.fbx.meta
  Unholy/Assets/Animations/Monster/B_Normal_Attack2.fbx.meta
  Unholy/Assets/Materials/FX.meta
  Unholy/Assets/Materials/FX/Spark.mat
  Unholy/Assets/Materials/FX/Spark.mat.meta
  Unholy/Assets/Prefabs/FX.meta
  Unholy/Assets/Prefabs/FX/ParrySpark.prefab
  Unholy/Assets/Prefabs/FX/ParrySpark.prefab.meta
  Unholy/Assets/Prefabs/FX/WeaponSpark.prefab
  Unholy/Assets/Prefabs/FX/WeaponSpark.prefab.meta
  Unholy/Assets/Prefabs/Monster/minotaur1.prefab
  Unholy/Assets/Prefabs/Player/Player.prefab
  Unholy/Assets/Scenes/Global Volume Profile.asset
  Unholy/Assets/Scenes/Global Volume Profile.asset.meta
  Unholy/Assets/Scenes/Monster/Monster.unity
  Unholy/Assets/Scripts/Monster/MinoController.cs
  Unholy/Assets/Scripts/Player/PlayerAttackCollision.cs
  Unholy/Assets/Scripts/Player/PlayerController.cs
  Unholy/Assets/Settings/URP-HighFidelity.asset
  Unholy/Assets/Shader.meta
  Unholy/Assets/Shader/Distortion.mat
  Unholy/Assets/Shader/Distortion.mat.meta
  Unholy/Assets/Shader/Distortion.shadergraph
  Unholy/Assets/Shader/Distortion.shadergraph.meta
Labels: enhancement

#107 fix: 패링 시 패링 이펙트 중첩 발생 (#106)
  Unholy/Assets/Animation Controller/MinoController.controller
  Unholy/Assets/Prefabs/FX/ParrySpark.prefab
  Unholy/Assets/Prefabs/Monster/minotaur1.prefab
  Unholy/Assets/Scenes/Monster/Monster.unity
  Unholy/Assets/Scripts/Monster/MinoController.cs
Labels: bug

#111 feat: 전투 특수효과 (#110)
  Unholy/Assets/Prefabs/FX/Blood.prefab
  Unholy/Assets/Prefabs/FX/Blood.prefab.meta
  Unholy/Assets/Prefabs/Monster/minotaur1.prefab
  Unholy/Assets/Prefabs/Player/Player.prefab
  Unholy/Assets/Scenes/Monster/Monster.unity
  Unholy/Assets/Scripts/Monster/MinoCollider.cs
  Unholy/Assets/Scripts/Player/PlayerAttackCollision.cs
  Unholy/Assets/Shader/Blood.mat
  Unholy/Assets/Shader/Blood.mat.meta
Labels: enhancement

#112 [Feat] UI 연동 (#94)
  Unholy/Assets/Animation Controller/PlayerController.controller
  Unholy/Assets/Animations/Monster/B_BA_Attack.fbx.meta
  Unholy/Assets/Animations/Monster/B_Jump_Attack.fbx.meta
  Unholy/Assets/Animations/Monster/B_Kick_Attack.fbx.meta
  Unholy/Assets/Prefabs/Monster/minotaur1.prefab
  Unholy/Assets/Prefabs/UI.meta
  Unholy/Assets/Prefabs/UI/UI Manager.prefab
  Unholy/Assets/Prefabs/UI/UI Manager.prefab.meta
  Unholy/Assets/Prefabs/UI/slots.prefab
  Unholy/Assets/Prefabs/UI/slots.prefab.meta
  Unholy/Assets/Resources/LoadingUI.prefab
  Unholy/Assets/Resources/LoadingUI.prefab.meta
  Unholy/Assets/Resources/UI/TutorialPopup 1.png
  Unholy/Assets/Resources/UI/TutorialPopup 1.png.meta
  Unholy/Assets/Scenes/Character.unity
  Unholy/Assets/Scenes/UI/PlayScene.unity
  Unholy/Assets/Scenes/UI/PlayScene/NavMesh-Floor.asset
  Unholy/Assets/Scenes/UI/PlayScene/NavMesh-Floor.asset.meta
  Unholy/Assets/Scenes/UI/TitleScene.unity
  Unholy/Assets/Scripts/CombatManager.cs
  Unholy/Assets/Scripts/Data.meta
  Unholy/Assets/Scripts/Data/SceneIndex.cs
  Unholy/Assets/Scripts/Data/SceneIndex.cs.meta
  Unholy/Assets/Scripts/Data/StaminaValues.cs
  Unholy/Assets/Scripts/Data/StaminaValues.cs.meta
  Unholy/Assets/Scripts/Data/WeaponType.cs
  Unholy/Assets/Scripts/Data/WeaponType.cs.meta
  Unholy/Assets/Scripts/Monster/MinoCollider.cs
  Unholy/Assets/Scripts/Monster/MinoController.cs
  Unholy/Assets/Scripts/Player/PlayerController.cs
  Unholy/Assets/Scripts/Player/PlayerInputs.cs
  Unholy/Assets/Scripts/Player/PlayerInputs.inputactions
  Unholy/Assets/Scripts/Player/StateBehaviour/DamagedBehaviour.cs
  Unholy/Assets/Scripts/UI/LoadingManager.cs
  Unholy/Assets/Scripts/UI/LoadingManager.cs.meta
  Unholy/Assets/Scripts/UI/QuickSlots.cs
  Unholy/Assets/Scripts/UI/QuickSlots.cs.meta
  Unholy/Assets/Scripts/UI/TitleSceneManager.cs
  Unholy/Assets/Scripts/UI/TitleSceneManager.cs.meta
  Unholy/Assets/Scripts/UI/UIHudManager.cs
  Unholy/Assets/Scripts/UI/UIHudManager.cs.meta
  Unholy/Assets/Scripts/UI/UIManager.cs
  Unholy/Assets/Scripts/UI/UIPopUp.cs
  Unholy/Assets/Scripts/UI/UIPopUp.cs.meta
  Unholy/Assets/Scripts/UI/UIStatBar.cs
  Unholy/Assets/Scripts/UI/UIStatBar.cs.meta
  Unholy/Assets/Scripts/UIStatBar.cs
  Unholy/Assets/Settings/URP-Balanced.asset
  Unholy/Assets/Settings/URP-HighFidelity.asset
  Unholy/Assets/Settings/URP-Performant.asset
  Unholy/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  Unholy/ProjectSettings/BurstAotSettings_StandaloneWindows.json
  Unholy/ProjectSettings/CommonBurstAotSettings.json
  Unholy/ProjectSettings/NavMeshAreas.asset
  Unholy/ProjectSettings/ProjectSettings.asset
Labels: enhancement

#114 fix: CombatManager / _longDefense 삭제 이슈 (#113)
  Unholy/Assets/Animation Controller/MinoController.controller
  Unholy/Assets/Animation Controller/PlayerController.controller
  Unholy/Assets/Animations/Monster/B_BA_Attack.fbx.meta
  Unholy/Assets/Animations/Monster/B_Jump_Attack.fbx.meta
  Unholy/Assets/Animations/Monster/B_Kick_Attack.fbx.meta
  Unholy/Assets/Prefabs/Monster/minotaur1.prefab
  Unholy/Assets/Scenes/Character.unity
  Unholy/Assets/Scripts/CombatManager.cs
  Unholy/Assets/Scripts/Monster/MinoCollider.cs
  Unholy/Assets/Scripts/Monster/MinoController.cs
  Unholy/Assets/Scripts/Player/PlayerController.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/ComboAttackBehaviour.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/DamagedBehaviour.cs
  Unholy/Assets/Scripts/Player/StateBehaviour/DeathBehaviour.cs
  Unholy/Assets/Scripts/UI/TitleSceneManager.cs
  Unholy/Assets/Scripts/UI/UIPopUp.cs
  Unholy/Assets/Scripts/UI/UIStatBar.cs
  Unholy/Assets/Settings/URP-Balanced.asset
  Unholy/Assets/Settings/URP-HighFidelity.asset
  Unholy/Assets/Settings/URP-Performant.asset
Labels: bug, enhancement

#116 feat: 전체 기능 통합 (#105)
  Unholy/Assets/Scenes/UI/PlayScene.unity
  Unholy/Assets/Scenes/UI/PlayScene/NavMesh-BossField.asset
  Unholy/Assets/Scenes/UI/PlayScene/NavMesh-BossField.asset.meta
Labels: enhancement
